### ISSUE TITLE
Support consuming cloud PVs, multi-host subdots and failover on cloud volumes (aka CVv2)

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#100]
See [design doc](https://docs.google.com/document/d/1OTTk8pmxWYQ6L4YN6v14OrGKXn_zSWTfCaaWGObvsrQ/edit).

Research:

- [x] Work out how to get ZFS in a PV: https://github.com/dotmesh-io/dotmesh/issues/333
- [x] Work out how to migrate NFS with ZFS: https://github.com/dotmesh-io/dotmesh/issues/334
- [x] Work out how to control our allocation to nodes: https://github.com/dotmesh-io/ops/issues/9
- [x] Investigate failover when using a service vip for an NFS server: https://github.com/dotmesh-io/dotmesh/issues/335

Work:

- [x] Support zpool in a PV #342 
- [x] Develop a StatefulSet template to run Dotmesh for a given cluster size #343
- [x] Write a basic Dotmesh Operator to instantiate our StatefulSet template #385 -> #344
- [x] Automatically generate unique pool names #348 
- [ ] Modify/configure Ganesha to produce file handles that are stable across migrations: https://github.com/dotmesh-io/dotmesh/issues/341
- [ ] Add NFS server into Dotmesh server #345
- [ ] Write an NFS+Dotmesh Flexvolume driver #346
- [ ] Modify the Dotmesh Operator to run a configurable pool of Dotmesh "server" nodes with PVs + the FV driver installed on every "client" node #385-> #347

**Comment by alaric-datamesh** [comment]
Closed as it's in the ideas list at https://docs.google.com/document/d/1tEl-hLmnf5trfAJZMm9-F6lW4G0BAJk0_1vxl3rgpTE/edit# - we can re-open when we actually do it.

**Comment by alaric-datamesh** [comment]
Re-opening as we're doing it!

Roadmap item: https://github.com/dotmesh-io/roadmap/issues/10

**Comment by lukemarsden** [comment]
Note that https://github.com/dotmesh-io/dotmesh/issues/344#issuecomment-379320582 includes an action plan based on TDD. Let's proceed with that next.

**Comment by lukemarsden** [comment]
Closing as we're not working on any more of this soon.
