### ISSUE TITLE
Dotmesh Operator

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#385]
Moving "bigger picture" tasks out of https://github.com/dotmesh-io/dotmesh/issues/344

- [x] #344 Basic local-storage-only operator that just wraps the existing behaviour
- [x] Do we want the operator to also set up other stuff from the Dotmesh yaml file, like service accounts, the dynamic provisioner, and all that? - no we don't, to make it easier for people to see what's going on and customise it by hand-editing the YAML.
- [x] Configuration for the local storage mode to allow specifying a different pool size and path
- [x] #401 PV-per-node storage mode, with PV size and storageclass configurable.
- [x] #463 Stop Kubernetes breaking our zpools
- [ ] #426 Multi-PV-per-node support, so orphaned PVs get brought up on a node by running two dotmeshes on one node.
- [ ] #347 Full NFS-based CVV2 mode, with the number of storage nodes configurable (depends on #341, #345 and #346 and the unissued final bullet in #100)
- [ ] #417 Multi-AZ support

This is part of epic #100.

**Comment by lukemarsden** [comment]
Closing as we're not doing any more of this for a while.
