### ISSUE TITLE
EPIC: Kubernetes support

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#45]
- [x] Install Datamesh on Kubernetes with a kubectl one-liner
- [x] Have Datamesh provide FlexVolume and Dynamic Provisioning
- [x] Figure out how to expose all Datamesh features through Kube YAML
- [x] StorageClass or another API object which provides automatic snapshots & replication

Design doc: [here](https://docs.google.com/document/d/1WcFdI_Gmgfq7JV_s8RJvt9vlPrj9O_Q_Nd-fSJ5M0PI/edit).
