### ISSUE TITLE
Get CI green

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#525]
As developers, we want to have working CI for the Dotmesh core product, so we can deploy new code to production and know when we've broken something.

As such, we should make sure that:

- [x] There are no non-flake issues blocking CI: It is possible to get a run through e2e testing, and deployed to the dothub, and smoke tests passing.
- [x] The flakes (those being: things that cause a CI job to fail, but retrying it makes it pass) are mitigated to a reasonable extent by automating retries or, where possible, fixing underlying issues.

# sub-issues (on bionic)

- [x] #513: runners are still rebooting 
- [ ] #534: a legit 0.7 zfs issue `error-rpc-predict-size`
- [ ] #535: the dind flexvolume provisioner can't cope with the sentinel AND dotmesh trying to use the same PVC
- [ ] #493: re-enable the Divergence test if it's passing now

**Comment by alaric-dotmesh** [comment]
Done enough!
