### ISSUE TITLE
Foundational stability fortnight!

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#592]
There are a set of known architectural issues in dotmesh which make us nervous.

Let's have a focused sprint to design & implement fixes for them.

Please add links to issues to this issue!

- [ ] https://github.com/dotmesh-io/dotmesh/issues/186
- [ ] Deletion is flaky (should be helped by the above)
- [ ] https://github.com/dotmesh-io/dotmesh/issues/34
